config/routes.rb
Rails.application.routes.draw do

  get 'sales/new'

  get 'sales/update'

  get 'sales/index'

  get 'stocks/new'

  get 'sessions/new'

  #match '/stocks/new/', to: 'stock#new', as: 'new_stocks'
  root 'static_pages#overview'
  root 'sessions#new'
  get '/inventory', to: 'static_pages#inventory'
  get '/overview', to: 'static_pages#overview'
  get '/orderhistory', to: 'static_pages#orderhistory'
  get '/finances', to: 'static_pages#finances'
  get '/employees', to: 'users#index'
  get '/providers', to: 'provider#index'
  get '/addprovider', to:'provider#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/bls/index', to: 'bls#index'
  get '/stocks', to: "stocks#index"
  get '/sales/quantity', to: "sales#quantity"
  post '/login', to: 'sessions#create'
  post '/providers', to: 'provider#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :medicines
  resources :bls
  resources :stocks
  resources :providers
  resources :sales
  resources :sales_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/provider.rb
class Provider < ApplicationRecord

validates :name, presence: true
#No need to force the address
validates :phone, numericality: { only_integer: true, allow_nil: true  } #, presence: true


end

app/controllers/provider_controller.rb
class ProviderController < ApplicationController

def new
    @provider = Provider.new
  end
 
  def show
    @provider = Provider.find(params[:id])
  end

  def index
    @provider = Provider.paginate(page: params[:page], per_page:20)
  end
  
   def create
  	@provider = Provider.new(provider_params)
  	if @provider.save
  		flash[:success] = "Inscription avec succés!"
  		redirect_to '/providers'
  	else 
  		render 'new'
  	end
  end
  
  
  private
  	def provider_params
  		params.require(:provider).permit(:name,:address,:phone)
  	end
	
	
end

app/helpers/provider_helper.rb
module ProviderHelper
end

app/views/provider/index.html.erb
<% provide(:title, 'Liste des Fournisseurs') %>



<%= will_paginate %>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
  	<tr>
  		<th scope="col">#</th>
  		<th scope="col">Nom</th>
  		<th scope="col">Téléphone</th>
		<th scope="col">Addresse</th>
  	</tr>
  </thead>
  <tbody>
  	<% @provider.each_with_index do |provider, n| %>
  		<tr>
  			<th scope="row"><%= n %></th>
    		<td>
      			<%= link_to provider.name, providers_path %>
    		</td>
    		<td>
    			<%= link_to provider.phone, providers_path %>
   		 	</td>
			<td>
    			<%= link_to provider.address, providers_path %>
   		 	</td>
   		</tr>
  	<% end %>
  </tbody>
</table>

<%= link_to "Ajouter un Fournisseur", addprovider_path, class: "btn btn-primary" %>

<%= will_paginate %>

app/views/provider/new.html.erb
<% provide(:title, "Créer un Fournisseur") %>
<!DOCTYPE html>
<html>
	<body>
		<div class="center">
			<%= form_for @provider do |f| %>
				<%= render 'shared/providers_error_messages' %>

     			<%= f.label :name %>
      			<%= f.text_field :name, class: 'form-control' %>

      			<%= f.label :address %>
      			<%= f.text_field :address, class: 'form-control' %>

     			<%= f.label :phone %>
      			<%= f.text_field :phone, class: 'form-control' %>

      		<%= f.submit "Créer un Fournisseur", class: "btn btn-primary" %>
    		<% end %>
		</div>
	</body>
</html>

app/views/provider/show.html.erb
<% provide(:title, "Fournisseurs") %>
<!DOCTYPE html>
<html>
  <body>
    <aside>
      <section class="provider_info">
        <h2>
     	    <%= @provider.name %>
        </h2>
        <h1>
      	 <%= @provider.phone %>
        </h1>
     </section>
    </aside>
  <body>
</html>