config/routes.rb
Rails.application.routes.draw do

  get 'sales/new'

  get 'sales/update'

  get 'sales/index'

  get 'stocks/new'

  get 'sessions/new'

  #match '/stocks/new/', to: 'stock#new', as: 'new_stocks'
  root 'static_pages#overview'
  root 'sessions#new'
  get '/inventory', to: 'static_pages#inventory'
  get '/overview', to: 'static_pages#overview'
  get '/orderhistory', to: 'static_pages#orderhistory'
  get '/finances', to: 'static_pages#finances'
  get '/employees', to: 'users#index'
  get '/providers', to: 'provider#index'
  get '/addprovider', to:'provider#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/bls/index', to: 'bls#index'
  get '/stocks', to: "stocks#index"
  get '/sales/quantity', to: "sales#quantity"
  post '/login', to: 'sessions#create'
  post '/providers', to: 'provider#create'
  delete '/logout', to: 'sessions#destroy'


  resources :users
  resources :medicines
  resources :bls
  resources :stocks
  resources :providers
  resources :sales
  resources :sales_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bl.rb
class Bl < ApplicationRecord

	#The IDs are obligatory and should be enforced to ensure the integrity of the database system.
	validates :provider_id, presence: true, numericality: { greater_than: 0 }
	validates :order_id, presence: true, numericality: { greater_than: 0 }, uniqueness: { case_sensitive: false }
	validates :user_id, presence: true, numericality: { greater_than: 0 }
	validates :finalpph, presence: true, numericality: { greater_than_or_equals: 0 }

	has_many :stocks
	has_many :medicines, through: :stocks
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	before_save { self.name = self.name.upcase }
	before_save { active_substance.upcase! } 
	before_save { self.name = "#{self.name} #{self.unit_gram} #{self.unit}"}
	
	validates :name, presence: true, length: { maximum: 49 }
	validates :barcode, numericality: { only_integer: true } , presence: true, uniqueness: { case_sensitive: false }
	validates :active_substance, presence: true, length: { maximum: 49 }
	validates :unit_gram, :numericality => true , presence: true
	validates :unit, presence: true
	validates :tva, presence: true

	has_many :stocks
	has_many :bls, through: :stocks
	has_one :tier
end

app/models/provider.rb
class Provider < ApplicationRecord

validates :name, presence: true
#No need to force the address
validates :phone, numericality: { only_integer: true, allow_nil: true  } #, presence: true


end

app/models/receipt.rb
class Receipt < ApplicationRecord

#We should discuss if empty Client names are a possibility.
validates :user_id , presence: true, numericality: { greater_than: 0 }
validates :finalpph , presence: true, numericality: { greater_than_or_equals: 0 }, allow_nil: true

has_many :medicinelogs

end

app/models/sale.rb
class Sale < ApplicationRecord
  before_save { self.total_price = self.quantity_sold.to_i * (Stock.find(self.stock_id).ppv.to_i) }

  validates :stock_id, presence: true, numericality: { greater_than: 0 }
  validates :quantity_sold, presence: true, numericality: { greater_than_or_equals: 0 }
  validates :total_price, presence: true, numericality: { greater_than_or_equals: 0 }
  belongs_to :stock
end

app/models/stock.rb
class Stock < ApplicationRecord

	before_save { self.medicine_name = "#{self.medicine_name} #{self.ppv} DHS"}
	#The IDs are obligatory and should be enforced to ensure the integrity of the database system.
	validates :bl_id, presence: true, numericality: { greater_than: 0 }
	validates :medicine_id, presence: true, numericality: { greater_than: 0 }
	#Medicine_Qt and Qt_Sold starts as the same amount. Qt_Sold decreases when a medicine gets sold.
	validates :medicine_qt, presence: true, numericality: { greater_than: 0 }
	validates :qt_sold, presence: true, numericality: { greater_than_or_equals: 0 }
	#PPH should exist as it determines the price of that unit.
	validates :pph, presence: true, numericality: { greater_than_or_equals: 0 }

	belongs_to :medicine
	belongs_to :bl
	


end

app/models/tier.rb
class Tier < ApplicationRecord

validates :name, presence: true, length: { maximum: 50 }
validates :value, presence: true, numericality: { greater_than: 0} 
validates :is_flat, presence: true #This boolean determines if the value will be added directly or if it is a percentage.

belongs_to :medicine
end

app/models/user.rb
class User < ApplicationRecord

	before_save { name.downcase! }
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	validates :occupation, presence: true, length: { maximum: 24 }
	validates :password, length: { minimum: 6 }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/bls_controller.rb
 class BlsController < ApplicationController

	$active_bl = nil
  def new
  	@bl = Bl.new
  end

  def nullify_active_bl
	$active_bl = nil
	end
	
  def create 
    @bl = Bl.new(bl_params)
    if @bl.save
      @bl = Bl.create(bl_params)
      flash[:success] = "Bon de livraison ajouté!"
	  $active_bl = Bl.last
      redirect_to stocks_new_path
    else
      render 'new'
    end
  end

  def index
    @bls = Bl.paginate(page: params[:page])
  end

  private 
    def bl_params
      params.require(:bl).permit(:provider_id, :order_id, :user_id, :finalpph)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Errachidia Pharmacy"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/bl_helper.rb
module BlHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/provider_helper.rb
module ProviderHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sales_steps_helper.rb
module SalesStepsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light">
    <!-- Brand Info -->
     <div class="row">
        <%= link_to image_tag("pharmacy.png", alt: "Pharmacy logo"), root_path %>
    </div>
    <div class="row">
        <ul class="nav nav-stacked navbar-left nav-pills">
            <a class="navbar-brand mb-0 h1">Pharmacie Errachidia</a> 
            <h6 class= "pad headers">Tableau de Bord</h6>                        
            <li class="nav-link"><%= link_to "Acceuil", root_path %></li>
            <li class="nav-link"><%= link_to "Inventaire", stocks_path %></li>
            <h6 class= "pad headers">Actions</h6>
<li class="nav-link"><%= link_to "Vendre", new_sale_path %></li>
            <li class="nav-link"><%= link_to 'Ajouter Médicaments au système', new_medicine_path, 
            data: { modal: true } %></li>
			<li class="nav-link"><%= link_to "Ajouter Bon de Livraison", new_bl_path %></li>
			<h6 class= "pad headers">Archives</h6>
            <li class="nav-link"><%= link_to "Historique des Ventes", sales_path %></li>
            <li class="nav-link"><%= link_to "Liste des Employés", employees_path %></li>
            <li class="nav-link"><%= link_to "Liste des Fournisseurs", providers_path %></li>
            <div id="modal-holder"></div>
            <% if logged_in? %>
                <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            <% else %>
                <li><% link_to "Log in", login_path %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<div class="container" id ="contents-limit">
  		<div class="row" >
  			<!-- Navigation Bar -->
    		<div class="col-sm-4 " id="nav-limit"> 			
    			<%= render 'layouts/header'%>
    		</div>
    		<!-- Right Container -->
    		<div class="col-sm-8">
    			<div class="row page-view">
              <div class="col-sm-8">
    					 <h5 class="headers">TABLEAU DE BORD</h5>
    					 <h2><%= yield(:title) %></h2>  
              </div>
              <!-- <div class="col-sm-4">
                  <div class="dropdown show">
                    <button class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Account
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <%= link_to "Profile", current_user, class: "dropdown-item" %>
                        <%= link_to "Setting", '#', class: "dropdown-item" %>
                        <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
                  </div>
              </div> -->
    				</div>
            <hr/>
                    <!-- Content -->
    				<div>
              <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
              <% end %> 
    					<%= yield %>
    				</div>
            <%= debug(params) if Rails.env.development? %>
          </div>
    		</div>
    	</div>
	 </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>

<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>

		<%= csrf_meta_tags %>
    
		<% stylesheet_link_tag 'login' if params[:action] == 'new' %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    	<%= render 'layouts/shim' %>
    	
	</head>
	<body class="login-background">
		<div class="container-fluid">
			<div class="row align-items-center vertical-center">
				<div class="col-sm-4 space"></div>
				<%= yield %>
				<div class="col-sm-4 space"></div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/modal.html.erb
<div class="modal fade" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le document contient <%= pluralize(@user.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_medicine_error_messages.html.erb
<% if @medicine.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le document contient <%= pluralize(@medicine.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @medicine.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_providers_error_messages.html.erb
<% if @provider.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le document contient <%= pluralize(@provider.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @provider.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>